#! /bin/sh

# This file is part of fsio, see <https://qu1x.org/fsio>.
# 
# Copyright (c) 2016 Rouven Spreckels <n3vu0r@qu1x.org>
# 
# fsio is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License version 3
# as published by the Free Software Foundation on 19 November 2007.
# 
# fsio is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with fsio. If not, see <https://www.gnu.org/licenses>.

if [ "$1" = revoke ]; then
	test -e Makefile && \
		make distclean
	rm -rf \
		README \
		aclocal.m4 \
		autom4te.cache \
		compile \
		config.guess \
		config.h \
		config.h.in \
		config.h.in~ \
		config.log \
		config.status \
		config.sub \
		configure \
		depcomp \
		INSTALL \
		install-sh \
		libtool \
		ltmain.sh \
		m4 \
		Makefile \
		Makefile.in \
		missing
else
	mkdir -p m4
	ln -sf README.md README
	autoreconf -i
fi
